### ISSUE TITLE
Suggestion: Export xpub for single account

### ISSUE THREAD

**Issue by ondra-novak** [mycelium-com/wallet#129]
Hi.
I am heavy user of mycelium wallet, it is great wallet for Android.

To support HD accounts is big and great step for this application, but still need some improvements

As far as I known, Bitcoin Trezor allows to export xpub (extended serialized public key) of external chain of the single hd-account. Please include this feature to the mycelium. It should allow standard "share" feature or copy key to the clipboard (similar to sign message)

Example of expected result: xpub6BAncmx64zH2wGABVkL51fX9xvvNEJ7sTqJgYUwquhx9XkjNtdN4JrAVqFXw6Kq6dw2uBoXN6eM7yPLSFaPCNZU7wP4Ka1shnt2TdbQeAeL

(generated at bip32.org)

Ondřej Novak

**Comment by Transisto** [comment]
This is so deeply needed, isn't there a way to generate that xpub from the backup list of word ?

**Comment by Giszmo** [comment]
+1

How is the status of this issue? I'd like to add a requirement. For my purpose I would need an infinite amount of such xpub keys and could live with infinite receiving addresses but I'm stuck with Mycelium not allowing me to export more than one (unused) address at a time.

Use case: I want to share addresses (or better yet xpub keys) with many people that will pay me later in many transactions. The work around is to give them several addresses each, so that address re-use is avoided but ideally I would give them an xpub key each.

To my knowledge, none of the top wallets allows exporting xpub keys apart from Trezor and some low level tools but the use cases are endless.

**Comment by Transisto** [comment]
The status is that is has been implemented in the last version.

**Comment by Giszmo** [comment]
Ah, got it. Well, ... hmm ... I see several issues.

1. With the current UI you will definitely find users that use that "export" of "HD wallet Account 1" as a backup. 
2. I see how this xpub key can be used to get the data I need in my case. Option one: I educate my users to export the xpub key and have my software derive to a level that doesn't compromise the whole wallet (BIP44 "m/44'/0'/0'/0/0") for example. Assuming Mycelium is BIP44 compliant, it will even find the payments received.) I would have to pinky swear to instantly forget m though. Option two: I educate them to /44'/0'/0'/0/* themselves but they would definitely screw up or not even try.

For my use case I had hoped for a "request payment" (maybe only in expert mode) where I directly would get the next xpub key instead of the corresponding address. Something where Mycelium would watch the next directly derived keys one by one (or 5 ahead). So instead of sharing the address of m/44'/0'/0'/0/* (if that's how Mycelium works) I would consider meaningful to share m/44'/0'/x'/0/ so that the recipient sequentially pays to m/44'/0'/x'/0/*. Mycelium should then watch m/44'/0'/x'/0/0..4.

**Comment by DanielWeigl** [comment]
ad. 1: Why do you think that users will think that the xPub-Key is their Backup? In the export screen we explicit state that you are unable to spend funds with it.

ad. 2: We export the m/44'/0'/x' xPub Key. So everyone who gets this key will see all transaction regarding this account (external and change-chain). If you want to have privacy, just use a dedicated account, which you only use for a certain service. Wouldn't that solve your scenario?

**Comment by Giszmo** [comment]
> ad. 1: Why do you think that users will think that the xPub-Key is their Backup?

Because it's reachable via "Account 1" -> "export"

> In the export screen we explicit state that you are unable to spend funds with it.

Users don't read. Especially those that are forced to use products in languages they don't understand perfectly. Is Mycelium localized to Chinese? Farsi? Mapudungun? Also less experienced users will get confused and do stupid stuff.

> ad. 2: We export the m/44'/0'/x' xPub Key.

So you export ''and use'' m/44'/0'/x'? So if I "create" account 2, this would actually not be a new m but m/44'/0'/1' ... ah, I start to understand. Sounds like this would actually work for the smarter users. So the instructions would go:

1. Create a new HD account in Mycelium.
2. (Name it to your purpose)
3. Export that account to my product

> So everyone who gets this key will see all transaction regarding this account (external and change-chain).

Ok, so to ease my bosses mind please confirm that with Account 2's xpub key being shared, the user would be able to spend Account 2's coins without using Account 2's change addresses? Which change addresses would be used in aggregate view? Account 1? Invisible account 0?

> If you want to have privacy, just use a dedicated account, which you only use for a certain service. Wouldn't that solve your scenario?

Again, if I share a pub key, I would want to receive money to that account but wouldn't want people who know that xpub key to also learn about what of my outputs are change and what are payments. I would require to be able to spend Account 2's coins with change going to Account 1's change addresses for example.

So if I got things right, I guess you did things the right way but failed to communicate it well enough for me to get it from the app alone. I was under the impression that the xpub key export would export m. Sure, now I feel a bit stupid but I bet I'm not the only one who despite knowing BIP44 doesn't immediately see how "Account 1" actually is a BIP44 account 1. For the average users it's probably smart to flatten the whole thing, as they will never user Account 2 or export xpub keys. I'll keep my others ideas on how this could resolved for a later reply as I'm not sure if I'm already far off track here ;)

**Comment by Giszmo** [comment]
I just confirmed for myself that it actually works for me. Thank you.

But the privacy issue remains. How can I share account 2 to 35 xpub keys with some 33 people and then go spend the money I receive to those using an account 1 change address? I can't find the old aggregate view where I would expect to be able to spend from multiple accounts at once. Would account 1 ask me about spending from other accounts if I exceed my funds? (It doesn't on a quick test.)

**Comment by ondra-novak** [comment]
ad 1: Export != Backup.

**Comment by DanielWeigl** [comment]
@Giszmo, what is your exact use-case? Do you want to share 33 xPubs? So that 33 people are able to make more than one transaction to you? Or do you only need to share 33 Addresses, which might came from the same account (=same xPub)?

But be aware, the BIP44 standard defines that the maximal gap between used addresses from one account is 20 - so if you share 33 addresses and all the first 20 do not send funds to their provided address, all after them would be ignored. They would be spendable if you use a customized client, but they wont be detected by our wallet (or any other based on BIP44) -> This is the reason we only allow to share one unused address per account.

Ad. aggregated view: You are correct, this was removed since the HD-Version. We want a strict separation of all accounts, so that you dont accidentally produce privacy subverting transactions. It is currently not possible to collect unspent outputs from different accounts - you would need to make one transaction per account and send them manually to an other account.

**Comment by ondra-novak** [comment]
Can mycellium create 20 receiving addresses on the single account? I can't find this function. I am always see just one address. 

Anyway, you can workaround 20 gap issue by creating 19 addresses and then send one output to 20th address. Then you can create additional 19 addresses and so on.

**Comment by jandreske** [comment]
No, mycelium currently does not allow creating more than one receiving address. We might add that in the future, but please keep in mind that mycelium is a mobile wallet - most pretty advanced use cases are maybe better conducted on a full featured desktop client. The app should stay easy enough to use for novice users - it's always a difficult balance between enabling possible use cases and keeping the overall complexity down.

**Comment by Giszmo** [comment]
> ad 1: Export != Backup.

You know that. Do all your users know that? I'm just suggesting that an Export functionality could be mistaken for a backup functionality and my bet would be that at least some 1% of the users would treat it like that. I would at least highlight a bit the explanation that indeed explains that it's not a backup. Also if I wanted a backup of just account 1, I could only use the export feature as there is no way to backup account 1 without account 2 (if I wanted to not put all my backups in one place for example).

> @Giszmo, what is your exact use-case? Do you want to share 33 xPubs? So that 33 people are able to make more than one transaction to you? Or do you only need to share 33 Addresses, which might came from the same account (=same xPub)?

33 people collect money into my wallet in many transactions each. I had convinced my boss that his app should not be a wallet itself, as this functionality of sharing the means to receive coins does not justify to deal with all the security implications that maintaining an actual wallet comes with, so now I just have to convince you to code this part of our app ;) No, seriously, I guess Mycelium is already there. Just neither my boss nor me did find the export feature or its relevance to our problem prior to chatting here. I will educate our users and hope our app does make a sufficient splash once it's out there so you reconsider improving usability. Anyway, Mycelium already is the best wallet out there.

@jandreske @DanielWeigl : the address gap limit certainly is a problem when restoring wallets from the seed. Allowing to skip 19 but not 20 would also somehow be awkward.

**Comment by ondra-novak** [comment]
I can see "Create Backup" as first entry of the menu. You cannot make mistake. Common user won't probably request to create separate backup for every account

**Comment by johnadair10** [comment]
Using the word "export" does seem vague in this sense.

BIP44 states that the "internal chain is used for addresses which are not meant to be visible outside of the wallet...", yet the only option of sharing xpub is more for the purposes of creating an AccountWatchOnly wallet. And thisApp that @Giszmo is working on needs an "external chain" only.

Maybe consider:
Share->AccountWatchOnly(xpub)
Share->MerchantPaymentStream(xpub)
Backup->Account(xprv)

**Comment by brasslan** [comment]
+1 for
Maybe consider:
Share->AccountWatchOnly(xpub)
Share->MerchantPaymentStream(xpub)
Backup->Account(xprv)

I would love to be able to give my employer an xpub without access to internal chains.

**Comment by DanielWeigl** [comment]
Why not use an dedicated account and share it with your employer?

And from time to time send everything to a different account.

Most bitcoin user won't understand the difference between those two types of xpubs and this will only lead to confusions. Also most people arent aware of change addresses.

Am 16. Mai 2015 10:30:28 MESZ, schrieb brasslan <notifications@github.com>:
>+1 for
>Maybe consider:
>Share->AccountWatchOnly(xpub)
>Share->MerchantPaymentStream(xpub)
>Backup->Account(xprv)
>
>I would love to be able to give my employer an xpub without access to
>internal chains.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mycelium-com/wallet/issues/129#issuecomment-102589309

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Giszmo** [comment]
Being able to export other than level 3 xpubs is subject to other issues. I guess we would merge a nice implementation to export other level xpubs but for now the features available must do. A BIP would be needed to improve handling of xpubs anyway as currently the only information that an xpub transports, is the level. And level 0 can mean many schemes for example.

Issues addressed here are better dealt with via stealth addresses or [BIP 47 reusable payment codes](https://github.com/bitcoin/bips/blob/master/bip-0047.mediawiki).
