### ISSUE TITLE
Bug: Cannot type multiple 0s if first number is 0 in Request Amount 

### ISSUE THREAD

**Issue by ticoombs** [mycelium-com/wallet#145]
If first number is 0 in a request amount. No more 0's can be added to the number. 

Example value not working :
0910023.00 (can't type another 0 unless it's after a decimal point) you will physically unable to type the middle two 0's 

Example value that works:
100066000.00

**Comment by johnzweng** [comment]
I can reproduce this problem.

Apparently the problem lies here: [NumberEntry.java - line 115](https://github.com/mycelium-com/wallet/blob/master/public/mbw/src/main/java/com/mycelium/wallet/NumberEntry.java#L115)

As the comment suggests this check should prevent that more than one leading 0s can be entered, but in  the current form it makes it impossible to enter any furtjer zeros at all if the entered amount starts with 0 and has no dot "." entered yet.

**Comment by johnzweng** [comment]
Created a pull request which changes this behaviour:
https://github.com/mycelium-com/wallet/pull/146

**Comment by ticoombs** [comment]
LGTM! @johnzweng next coffee is on me @changetip

**Comment by changetip** [comment]
Hi @johnzweng, @ticoombs sent you a Bitcoin tip worth 1 coffee (5,614 bits/$1.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/343332)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by DanielWeigl** [comment]
Thx @johnzweng for the help - the change is merged internally and will be in the next release.

**Comment by johnzweng** [comment]
@ticoombs thanks. 
You are welcome. :-)
