### ISSUE TITLE
Cannot abort bitcoin payment

### ISSUE THREAD

**Issue by romanix** [mycelium-com/wallet#155]
Real world use case:

You use mycelium to pay for beers in a bar.
You scan the bar's QR code and pay.
The mobile phone connects using the telco network.

After a while you notice that something is not quite OK. The bar hasn't received anything yet.
After some trouble shooting you understand that the bar has a internet connectivity problem and the bar's tablet has only Wifi no 3G, 4G, ...

You lose your patience and decide to pay with fiat currency - but wait I can't abort the bitcoin transaction - although it hasn't been confirmed yet. (It's in status "sending"). Ok, you pay with fiat money and the bar will also receive the bitcoin payment (once they're connected). That's the real world double spend problem.

In fact it was even worse, because another guy (no names ...) thought it's a mycelium issue - he used another wallet to pay the bill. Triple spend ...
https://blockchain.info/address/14WLAFpxF8TWC1aWAioa1LiSfa7hDRNxQH?filter=2

**Comment by mycelium-com** [comment]
Hi! 
If it would have been a connectivity problem with your phone, mycelium would have asked you whether you want to delete the transaction or queue it for later. Since mycelium worked and the transaction has been broadcasted, there is nothing we can do. The transaction is known to thousands of nodes, there does not exist a way to abort it, even if it has no confirmations yet (= it's not in a block). And this is good - because if you could do it, people would pay the beer, walk out of the bar, and then cancel the transaction. 
After you sent the money, you could have 
- created a hotspot  for the tablet so they can see the transaction on their own device- shown the transaction to them in your Mycelium app, if they trust you to not have a modified version of mycelium to trick them - shown the transaction on your phone using a third party block explorer (tap on the transaction hash in transaction details to easily do it) - have them consult any internet connected device like their own phone, desktop pc,... 
Wenn can't cancel transactions, we don't want to, and if someone accepts Bitcoin it's really their duty to make sure they can check transactions. 
Cheers, Jan 

-------- Ursprüngliche Nachricht --------
Von: romanix <notifications@github.com> 
Datum: 01.04.2015  22:49  (GMT+01:00) 
An: mycelium-com/wallet <wallet@noreply.github.com> 
Betreff: [wallet] Cannot abort bitcoin payment (#155) 

Real world use case:

You use mycelium to pay for beers in a bar.

You scan the bar's QR code and pay.

The mobile phone connects using the telco network.

After a while you notice that something is not quite. The bar hasn't received anything yet.

After some trouble shooting you understand that the bar has a internet connectivity problem and the bar's tablet has only Wifi no 3G, 4G, ...

You lose your patience and decide to pay with fiat currency - but wait I can't abort the bitcoin transaction - although it hasn't been confirmed yet. (It's in status "sending"). Ok, you pay with fiat money and the bar will also receive the bitcoin payment (once they're connceted). That's the real world double spend problem.

In fact it was even worse, because another guy (no names ...) thought it's a mycelium issue and used another wallet to pay the bill. Triple spend ...

https://blockchain.info/address/14WLAFpxF8TWC1aWAioa1LiSfa7hDRNxQH?filter=2
