### ISSUE TITLE
Testnet blockchain stuck

### ISSUE THREAD

**Issue by Plnt** [mycelium-com/wallet#159]
I mined testnet bitcoins on http://testnet.tbdice.org/ , yesterday. I redirected them to my Mycelium testnet wallet. But so far I didn't received any of them even though they already have 100+ confirmations. I think it may be related to this problem:
https://blog.blocktrail.com/2015/04/in-the-darkest-depths-of-testnet3-16k-blocks-were-found-in-1-day/

I checked couple of testnet block explorers - http://tbtc.blockr.io/, https://www.blocktrail.com/tBTC, https://testnet.coinprism.info/ . They are all over block 348k but for example https://test-insight.bitpay.com/ is still on 333k. I'm wondering if this isn't the same problem with Mycelium testnet backend servers.

Thanks!

**Comment by DanielWeigl** [comment]
Hello,

yes our testnet got stuck on a wrong fork (which was over 700 blocks long) - it should be running now again.

**Comment by DanielWeigl** [comment]
Hi again,

It seems our testnet database got out of sync because of the large blockchain reorganizations you linked above.

First it seemed like it catched up again, but today I discovered that the blockstorage is now corrupted - so I started a full rebuild, which will take around 1 or two days. We only have one testnet server, so there is no failover capacity - sorry.
