### ISSUE TITLE
Use a proper Free Software License to safeguard Mycelium's future

### ISSUE THREAD

**Issue by dllud** [mycelium-com/wallet#164]
As explained by @apetersson on #4, the Microsoft Reference Source License (MS-RSL) used by Mycelium does not provide [Stallman's freedom number 3](https://www.gnu.org/philosophy/free-sw.html):
> The freedom to distribute copies of your modified versions to others.

I believe the current license is detrimental to Mycelium's future:
1. It prohibits use of the code in forks, which means there will be no downstream projects contributing to Mycelium's code base. Worse, it also means that if/when the current copyright holders stop development no one will be able to fork and continue the project.
2. It discourages contributions from independent developers.
3. It makes Mycelium lag behind virtually all other Bitcoin wallets.
4. It prevents Mycelium from being distributed on F-Droid.

I can see no reason why Mycelium needs to use MS-RSL. If development efforts continue at the current pace no fork will take you over.

Mycelium should thus switch to a license such as Apache or GPL (if you want to make sure the community gives back).

**Comment by Giszmo** [comment]
dllud you invited me to comment here, so I comment:

Mycelium highly depends on a proprietary server, so it's not like you could just fork the client and start your own thing. Also they have a tendency of going more closed, not more open. I'm thinking of that Trusted Computing thing they have in the making if I remember right, what was the name again?

Also I'm sure the issue was brought up before.

That said, I will stick with Mycelium for now but I would celebrate, too if it went with an open license.

**Comment by jandreske** [comment]
We, the developers, fully agree and would love to see the full source under Apache license. We just asked our investor (again) to please consider switching. We will of course let you know if we finally succeed.

**Comment by Rassah** [comment]
1. We have no issues with anyone contributing to Mycelium codebase, just as long as the final code is implemented in the main Mycelium version. If for whatever reason development stops, that would be either because the project is abandoned (it would be opensourced), or the company folded (it would likewise become opensourced).
2. Agreed, though we still have independent developers helping out at times. Ideally, of course, we would love a whole lot of independent developers helping.
3. So far Mycelium is way way way ahead of all other bitcoin wallets, so that's not a problem.
4. F-Droid is one app store. You can just download Mycelium directly from our website, so it's not that big of a deal.

While we do depend on a proprietary server, that's only to receive address balances, broadcast transactions, and for our LocalTrader function. We may also eventually use our servers for CoinJoin announcements, so people can easily mix their coins. And we do plan to add SPV support so that the wallet is still usable if our servers become unavailable for whatever reason. Other than that, we are actually trying to be more open, not less. The Trusted Computing thing is actually us opening the wallet for two third-parties to add their own code to it to allow our wallet to use TEE built into phones. Just as we have added support for Trezor, and are allowing Ledger to add support for their wallet.

All that said, as Jan mentioned, we are trying to push to switch to open source license.

**Comment by Giszmo** [comment]
I'm glad to hear so much optimism to see Mycelium go open source at some point. My TEE comment was actually inspired by the bitpay/rivetz work and probably a lack of understanding of how TEE works. I did google but could not find a definite clue on how TEE works for open source software but I trust your word on that it would not require the TEE-app using app to use a closed source library.

To play the devil's advocate again: The assumption that a folding company had a say on whether the code gets open sourced seams flawed to me. If folding comes in form of an insolvency, the creditors might have a right to monetize on all assets in which case the open source proponents would only get it open sourced if they ponied up more money than any company that paid – maybe a million – to just have Mycelium go away for good.

**Comment by Rassah** [comment]
TEE will be a closed source library, running as a third-party add-on in our app.

**Comment by jandreske** [comment]
Putting Mycelium Wallet under a real open source license is supported by the developers, and we asked the owner of the IP to please do this. He is considering it, and since we cant do anything but wait for a decision, I'll close this issue now and lets all hope for the best.

**Comment by dllud** [comment]
This issue is not resolved then. It should be left open until the IP owner's decision.

**Comment by algazarra** [comment]
Why closing the issue if the decision wasn't taken yet? The issue persists. Leave it open.

**Comment by revi** [comment]
Should be left open until IP owner decides. There is no resolution (FIXED, WONTFIX) yet so it should be open.

**Comment by tigusoft-vm** [comment]
@jandreske is there a decision yet? that would be nice.

**Comment by jandreske** [comment]
@tigusoft-vm next major version (like in "the new mycelium wallet") will be truly open source, I have been told. Do not know which exact license, and when to expect it, and what the fate of the current code will be, though. But I guess it is good news nonetheless. :)

**Comment by Rassah** [comment]
Current code will remain as is (too much legal headache to change it). New code will be open source. Is license important in "it's free, whatever" code?

**Comment by fortran77** [comment]
Even though this is a closed issue, I will offer the following suggestion.

The license should be modified just enough that projects such as F-Droid can make APKs of Mycelium available. This will improve the confidence of some of the most skeptical users, without allowing source code exploitation by competitors.

In any case, competition is much more likely to come from wallets such as Coinomi and its clone UberPay than from any potential clone of Mycelium itself.

**Comment by Rassah** [comment]
We won't bother with the current wallet, since there are too many legal hurdles to jump through, but the new wallet is fully open source already.

**Comment by lrvick** [comment]
@Rassah Can you link to the new wallet you speak of? All I see is this repo, which still has the restrictive LICENSE file that prevents independant services such as F-Droid from  auditing the code and providing signed reproducable builds I can trust.

Many in the bitcoin community including myself choose to run open-source-only versions of Android without Play Store such as Paranoid Android, LineageOS, or CopperHeadOS. 

For us, F-droid is the only trusted place for us to obtain audited/signed builds of software for our devices and it is sad we can't use Mycelium today without lowering the security profile of our devices.

**Comment by Giszmo** [comment]
you can build this wallet and check the apk we release. the license doesn't forbid that and i beg you to do it. pull request if changes are needed to make this happen.
