### ISSUE TITLE
Mark trade initiator as flake

### ISSUE THREAD

**Issue by TheButterZone** [mycelium-com/wallet#177]
I currently have 17 out of 17 trades initiated by others stopped or timed out because they were flakes who ignored my ad text, etc. Can there be a button added that marks the trade initiator as a flake and limits their ability to waste anyone else's time?

**Comment by Giszmo** [comment]
Local trader has a serious scam problem and we are aware of that. Unfortunately, in a system where it's free to add accounts, it's pointless and costly to close those, so we focus on educating the users to only do in person trades. But we are also investigating on how to otherwise improve the situation. But Mycelium the company wants to stay out of being a middle man. Suggestions on how this could work are welcome.
