### ISSUE TITLE
Send funds as multiple transactions

### ISSUE THREAD

**Issue by FrancisPouliot** [mycelium-com/wallet#179]
Feature idea: the ability to send funds as multiple transactions.

How it works: feature is enabled in advanced settings. When sending funds, option appears to send funds as multiple transactions. Mycelium randomly separates what would have been 1 transaction into 2 transactions (randomly generated amounts).

**Comment by Perlover** [comment]
Why? For security?
I think it will not improve security because outputs of two transactions will point to one bitcoin address as i understand. And watcher will guess.
And if i will forget about enabled this feature i will have troubles with payees (BitPay and etc) - they will get not requested amounts to bitcoin address (invoice) and cannot be able to account this as one payment. Shops may ignore payment as payment if payment will be splitted.

**Comment by FrancisPouliot** [comment]
"outputs of two transactions will point to one bitcoin address"

that can be fixed if coins are sourced from two separate accounts no?

**Comment by jonathancross** [comment]
> For security?

Sending bitcoin sourced from multiple addresses has no inherent security benefits that I know of.

> that can be fixed if coins are sourced from two separate accounts no?

@Perlover was referring to the single *destination* address.  Since both transactions are going to the same place, the user is not gaining much in terms of privacy (I assume this is the reason you are requesting this?).  Guess this would be like a single iteration CoinJoin with only one participant.  Would be much better to implement real CoinJoin transactions (See #187).

The fact that this could break payment processors like BitPay also makes it a dangerous option to add.

**Comment by Giszmo** [comment]
Can we close this? I guess, payment processors all deal well with split payments, as enough users will pay a part and then the rest from that other wallet that it makes sense to just deal with it. I agree that it makes no sense even in the context of merge avoidance as the time correlation plus address reuse in the recipient would not confuse any snoopy investigator.
