### ISSUE TITLE
Mycelium doesn't allow screenshot of Backup

### ISSUE THREAD

**Issue by francwalter** [mycelium-com/wallet#181]
Hello

when I do a legacy backup I need to write down the checksum (16 letters) for my key.
Without this, I cannot restore the wallet. But when I try to make a screenshot of this, it is not allowed. 
At least I expect a switch to make it possible, as it should be users decision if he wants less security.
The switch could be default to forbid screenshots here.

frank

**Comment by jandreske** [comment]
We will not change this. It is a very bad idea to screenshot the password, it's impossible for good reasons.

**Comment by francwalter** [comment]
Please indicate me the exact file where this is made impossible, so I could make a clone with this "feature" disabled  or at least a setting to disable it. Thank!

**Comment by DanielWeigl** [comment]
For what do you need this encrypted backup then? It has the same security profile as a plaintext exported private key. Which you can already do in Accounts -> Export. Here you can mail it and whatever you like. But it is really not recommended and we surly wont include such a setting that goes totally against private key security, because the whole 2-factor idea of the backup makes no sense if you store both parts of the secret on the same, internet connected device.

**Comment by francwalter** [comment]
To write down the letters manually is an error source. 
The user could save the screenshot encrypted if he wants and/or could store the screenshot on a different place, not the phone, his decision. 

I think even the letter code should be able to be copied to the clipboard, which is neither possible.

With this strict way you bring the user to do the secureless export of the key.
