### ISSUE TITLE
Feature: CPFP (raising fee via child-pays-for-parent)

### ISSUE THREAD

**Issue by Perlover** [mycelium-com/wallet#186]
Due to recent SPAM attacks in Bitcoin network there would be nice to have this feature:

CPFP (raising fee via child-pays-for-parent)

LIke in Bitcoin Wallet
http://www.reddit.com/r/Bitcoin/comments/3dn7el/cpfp_raising_fee_via_childpaysforparent/

What do you think about this?

**Comment by Giszmo** [comment]
So you want a button next to the `rebroadcast` button that would create a transaction to yourself, using that other transaction's output? Guess that's slightly complicated to implement but we will consider it.

**Comment by Giszmo** [comment]
With a way to bump the fee, situations like in #311 would not arise (that often) as the user could start off with lower fees for his average transactions.

The fee bumping would (just like the normal transaction would) need a way to consider not only the current transaction but the full chain of unconfirmed parent transactions and potential CPFP transactions on other branches when setting the fee to priority or normal for example.

**Comment by dscotese** [comment]
I see the feature, but it is lacking.  The current CPFP feature does NOT allow you to choose your own fee, which is the simplest "... way to consider not only the current transaction but the full chain of unconfirmed parent transactions and potential CPFP transactions on other branches".

I have incoming BTC that I'm trying to spend, but the incoming transaction is almost 2k, so a single CPFP that is only about 1/8 the size doesn't have much effect.  The wallet already provides a link to a block explorer where the user can see the transaction chain and do their own math or just guesstimate the total size of unconfirmed transactions.  I suggest the feature be altered with an extra option to add your own fee.  In addition to "... to bump the fee to [something the user can't change]," we could add "... or enter how much you want to add to the fee (at least X btc or Y usd to pay for this extra transaction) below" followed by an amount box with the BTC/USD switcher next to it.

When someone gets around to collecting all the transactions in the unconfirmed chain and adding their sizes and fees so that the feature as it describes itself ("bump the fee to X per byte") can be accurate, only the internals would have to change.  Currently, what the software says is inaccurate because the bump only sets the fee for the new CPFP Tx, not itself the original one combined.

**Comment by Giszmo** [comment]
I implemented our CPFP and tested it to actuall do the following:
If tx1 unconfirmed and has unspent output, allow bumping.
Set the fee to satPerByteForBlockTarget(2) * (size(tx1) + size(txBump)) - fee(tx1).
This ignores unconfirmed parents and bumping children of tx1.
If that is not how the feature works, then please create a new issue. We have to fix it.

The current CPFP feature could be improved by using RBF in the CPFP transaction, so we can increase the CPFP in case it doesn't succeed. With RBF we could enable gentile bumping, to later bump more aggressively without creating more transaction spam.

**Comment by dscotese** [comment]
It looks like it does work that way.  I have to retract my claim "the bump only sets the fee for the new CPFP Tx, not itself and the original one combined."  In fact, that is exactly what it does, as you described.  I didn't realize that what I really wanted to do was bump the fee on unconfirmed ancestor transactions (what I think you mean when you wrote "unconfirmed parents").

The unconfirmed ancestor in my case is 1873 bytes with a 53.39 SatoshiPerByte fee (of 0.001).  To cover that, I'd need a fee of about .008 and I don't see a way to do it.  Anyway, thanks for taking a look.

**Comment by alanrburns** [comment]
Hi 
I have spent hours looking for any information on this feature.
Is is actually implemented?
How do I do it in mycelium?

**Comment by Giszmo** [comment]
@alanrburns in the transaction history, select your unconfirmed transaction. Now in the context menu you should see the option.
