### ISSUE TITLE
Why does app require access to microphone?

### ISSUE THREAD

**Issue by FrancisPouliot** [mycelium-com/wallet#194]
Hello,

I have been asked by a privacy consultant to enquire about why the app requires access to microphone. While it probably does not consist of a privacy vulnerability, some of his clients may be worried about this particular permission on their secure devices.

**Comment by janschejbal** [comment]
Where do you see that it requires access to the microphone? I see no such thing in the permission list nor anywhere in the source code. Can you maybe provide a screenshot showing where you see that?

**Comment by Giszmo** [comment]
(I guess this might be a consequence of the camera permission that we use for qr-code scanning? I'd like to take privacy concerns seriously but in this case it's open source and can be reviewed to not do anything weird. android.permission.CAMERA is using the microphone and we need this permission to use the QR-Code scanner. We integrated the QR-Code scanner to not rely on potentially coin-stealing external implementation and thanks to the open source zxing libraries, it was possible to do so "easily".

A quick google lets me assume that the camera permission would allow to take videos from a background service, which would be scary, so I understand the concern and wished Android would allow to limit camera to only the image stream but for now I can only suggest to compile it yourself if you don't trust our binary, or better yet help us get deterministic builds, so that you can trust our binary to be what's in the play store.)
