### ISSUE TITLE
Fee calculation has been very problematic this whole day.

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet#239]
Low-prio 0.02172 mBTC
Economi 0.02581 mBTC
Normal    0.04386 mBTC
Priority    0.2590 mBTC

I find the step to be high between Normal and Priority. Could there be a middle ground ?

Example https://live.blockcypher.com/btc/tx/d529c5c95f7dc884c601e530cb3783b3b5949987aa2c72a121eed325651890ff/

Been waiting 4 hours for this transaction with a 0.00007452 BTC fee (Normal)

**Comment by Giszmo** [comment]
The fees are not arbitrary numbers but try to achieve a certain confirmation target and come from a full node's fee estimation. Normal fees should confirm in the "next block or two" but with overall traffic ramping up, while blocks are slowing down randomly, you can fall off the cliff for several blocks even with normal fees. If you absolutely need express payment, you essentially have to pay a priority treatment and  anything less would be a level of recently not mined transactions.

In the end, it's a random process when you expect random miners to mine your transaction and we can only try to improve our guess but more options will only complicate the process without giving good certainty about the confirmation speed.

**Comment by Giszmo** [comment]
The transaction has long been confirmed, with 7452sat paid for 373 bytes. That's 20sat per byte, mined in a full block where the average fee was 30sat per byte.

That is expected behavior and there is no need to tweak the fees.

Unfortunately there is a lot of randomness involved here. Blocks getting mined faster or slower. Others paying higher or lower fees. Others flooding the network with transactions or not. Miners deciding to include transactions or not.
