### ISSUE TITLE
Rendering errors when changing system DPI

### ISSUE THREAD

**Issue by Giszmo** [mycelium-com/wallet#240]
This bug was reported by mail. We have to look into it.

> just wanted to let you know that the Mycelium UI does not render properly if 
> the following Android 6 system setting is changed:
> 
> Settings / Device / Display & lights / Interface / LCD density
> 
> I've changed it from 480 to 400 DPI on my device, and this causes some of the 
> UI elements around the menu buttons to be misplaced.

**Comment by xor-freenet** [comment]
Original reporter here with some more information:

I'm not 100% sure from googling, but it is possible that this setting is not available on stock Android, but rather requires CyanogenMod. Given that CyanogenMod has millions of users, and nowadays is also installed on regularly sold phones, I would be glad if you could fix this nevertheless.

Some Google results for "android change dpi" say that this can also be done with adb, so you don't need CM to test it.

**Comment by Giszmo** [comment]
Ok, with `adb shell wm density 400` I can try this out on my virtual device.

Yes, changing the density for lower values makes the layout look more tablet-like and higher values more old-old-old-and-tiny-phones like.

Attached see my main screen with density 200
![200](https://cloud.githubusercontent.com/assets/96378/12500583/3ab53e5a-c093-11e5-80f5-597181f2be00.png)
400
![400](https://cloud.githubusercontent.com/assets/96378/12500586/415c9668-c093-11e5-9a18-8dafd61e3d49.png)
600
![600](https://cloud.githubusercontent.com/assets/96378/12500589/4361cad2-c093-11e5-8976-6f0f502971a6.png)
 and 800
![800](https://cloud.githubusercontent.com/assets/96378/12500590/45ae5eb8-c093-11e5-93be-3149bdb3140a.png).

While I see that we won't win a design award with this layout, is there any usability issue from that?

Ok, Local Trader has some Issues in portrait mode:
![screenshot from 2016-01-21 23 08 18](https://cloud.githubusercontent.com/assets/96378/12500760/bf3622c4-c094-11e5-92f1-1410b80f02ef.png).

Guess we can fix some burning issues but won't redesign for more special cases all too soon as we are working on a next generation of the product. Pull requests would be welcome though.

**Comment by xor-freenet** [comment]
Hmm no, that's not the issues I have:
- The top right menu button's menu has its background not fully rendered, and the shadow also seems off:
![screenshot_20160122-052635](https://cloud.githubusercontent.com/assets/78502/12502564/a05b3f34-c0ca-11e5-8368-57d8924b9244.png)

- The background of the menu buttons is off:
![screenshot_20160122-051907](https://cloud.githubusercontent.com/assets/78502/12502570/ba5da994-c0ca-11e5-91b6-b27d8f6e3e2a.png)

- The background of the menu which appears when going to "MY ADS" and selecting an ad also does seem off:
![screenshot_20160122-053409](https://cloud.githubusercontent.com/assets/78502/12502573/cb3931c0-c0ca-11e5-8452-ed210a10f7dc.png)

- When I open a trade in the trade history, scroll up in the chat history, and click the thumbs up  / thumbs down icons, a message box appears. The background of that box doesn't fully render (which is why I don't do a screenshot so I don't have to bother to remove the private information from it)

- The circle which appears as a "loading"-symbol is actually two circles. I suppose they should instead be rendered right above each other so they appear as one?

I experience those issues with the CyanogenMod version cm-13.0-20160118-NIGHTLY-hammerheadcaf from https://download.cyanogenmod.org/?device=hammerheadcaf ... I would suspect that you don't need the particular Nexus 5 (aka hammerhead) version, as I think CyanogenMod has the UI code in a separate repository which is shared among all devices.

Should have screenshotted this along with the initial report, sorry.
Thanks for your effort to create screenshots yourself! :)

**Comment by Giszmo** [comment]
Thank you for the details. Really looks report-worthy :frowning: But for now I don't know if that's even a Mycelium bug or maybe a Cyanogen bug. Don't hack your device :wink:

We will investigate and let you know.

**Comment by xor-freenet** [comment]
:)
I also considered that this may be an issue due to the fact that I'm using a develpment version but I've installed something like a dozen apps now, and I've only seen this at Mycelium and one other app (ColorNote). So I hope this can provide you some indication of the probability of this being a Mycelium issue.

**Comment by Giszmo** [comment]
Sorry but if your alpha OS fails to render 2 out of 12 apps correctly, I would highly tend to wait for the final release and beg you to report it to cyanogen and not to us. We are talking niche of a niche of a niche problems here.

Please re-open when the final version is out and cyanogen rejected to take responsibility.

**Comment by xor-freenet** [comment]
OK, fair enough :)
