### ISSUE TITLE
Exporting transaction doesn't work when too many 1000+

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet#243]
There is no sign that Mycelium is doing anything when I tap "export transaction".

I have an account with 1500+ transactions with important labels, I wouln't mind waiting even half a day to have Mycelium export these labels. It seems like it abandon without an error message after 200-300tx

Thank you.

**Comment by Transisto** [comment]
Maybe the solution would be to export as file instead of a blob of text

**Comment by Giszmo** [comment]
#142 is somewhat related (in case somebody wants to jump at fixing this)

[Here](https://github.com/mycelium-com/wallet/blob/master/public/mbw/src/main/java/com/mycelium/wallet/activity/modern/ModernMain.java#L334) the data gets added to an intent that gets handled by whatever. If you send it to Twitter, Twitter will limit it to 140 chars. Other apps may apply other limits. The IPC should work to a limit of 1MB, which should be good for about 6000 transactions. Less if you have a lot of lables. (Please use additional HD accounts if you are such a power user. It's for your own convenience and privacy.)

As a company we have to assume that more and more people will get into the range of thousands of transactions with more and more meta data, so the export should probably be handled wie a file attachment instead of a plain text if size is really the issue.

@Transisto could you please share which phone you are using? Independently we have to try this out with thousands of transactions, too.

**Comment by Giszmo** [comment]
I guess this will be fixed with the next release. There's still some `TODO`s. See patch.

[csvFileBasedPatch.txt](https://github.com/mycelium-com/wallet/files/147646/csvFileBasedPatch.txt)

**Comment by Transisto** [comment]
Seems to be not working starting arround 800 transactions.  Nowhere near
6000.  On galaxy a S6

**Comment by Giszmo** [comment]
Ok, then this change might be necessary starting at even more transactions than what you have but not fix another issue? I understood your reply as saying that you tried my patch?

I did not dig deep into the internals where the transactions get pulled from as I can now export 8000 times my three lines of transaction + header. The mail takes forever to show up on my laptop but it eventually arrives, with the data.

**Comment by Transisto** [comment]
No sorry I didn't run the patch,  I don't know how to compile mycelium.

**Comment by Giszmo** [comment]
Ok, don't bother. I suppose/hope this fixes your problem and didn't lose much time looking elsewhere. Just some clean-up and it's ready for the next release.

**Comment by DanielWeigl** [comment]
Can you try if it works with 2.7.3 now?

**Comment by Transisto** [comment]
It work perfectly, than you very much.
