### ISSUE TITLE
deterministic output order use (fixes user lost funds making same transaction twice)

### ISSUE THREAD

**Issue by tphyahoo** [mycelium-com/wallet#258]
problem: 

https://www.reddit.com/r/Bitcoin/comments/4cfw6t/psa_mycelium_ios_sends_even_when_it_appears/

as I commented:

"Thinking about this, seems that it would be a good idea if wallets deterministically spent outputs. Then if a wallet accidentally rebroadcasted the same wanted transaction twice, without knowing the first was already gone, the second would fail because it used same outputs."

Reasonable?  Maybe something all wallets should do?

UPDATE:

I don't actually know nondeterministic coin selection is cause of problem.

It could also be a bug where coin selection coin knows about the spent coins, but the user doesn't see this in the wallet history because of delay bug.

UPDATE 2:

from link above "/u/rassah wrote this about a year ago. This bug only appears on a small number of iOS devices, and the developer can't even reproduce it on his own phone. It seems to have to do with the way iOS or Apple stores TouchID protected items. If you have this problem, please e-mail ios@mycelium.com so he can debug this issue, because it works perfectly on our devices, and our dev needs a broken version to see what actually went wrong."

I'll let mycelium developers decide if this issue is spurious.

**Comment by Giszmo** [comment]
The linked reddit discussion is about a clear bug, while here you propose a feature I'm not sure has anything to do with the bug. In Mycelium, you normally don't have tons of outputs to spend from, which leads me to believe that the user even spent from the change output instead of accidentally spending from different UTXOs. TX-ids would be nice to have to confirm that.

Now **if** the history would be working, with just the history display being off, you could argue that a warning about a suspicious double-payment might protect some users. "Attention! Your last transaction was to the same address with (almost) the same amount! Are you sure you want to pay this address twice?" but that would be a different thing.

Due to the very small chance of such an exact feature as you proposed protecting anybody, I'll close this issue.
