### ISSUE TITLE
can only import level 3 xpub

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet#289]
... This is level 0

While trying import by scan an xpub from electrum.

**Comment by Giszmo** [comment]
Yes, importing xpubs is limited to BIP44 level 3. This is because BIP32 level 0 is ambiguous and therefore can't be handled consistently with Mycelium. (It could if we added some questions about where the xpub came from.

With more schemes using level 3 xpubs, we might have to revise this and add the questions anyway.

The xpub not telling which schema it uses is really unfortunate but with it being the way it is, things can easily get out of control and we decided to only support (and assume) BIP44 xpubs here.
