### ISSUE TITLE
Support for Level 0 xPub (electrum)

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet#300]
Why can Mycelium only import level 3 xPub ?

**Comment by Giszmo** [comment]
Mycelium already puts quite strong assumptions into accepting level 3 xpubs as account level xpubs. Mycelium is advertised as a BIP44 wallet and as such does also handle imported xpubs as compliant with this standard. All standards have some level 0 xpub but with very different meanings. Level 3 xpubs are to my knowledge only exportable on BIP44 wallets, so there is no big risk of confusion.

If you want to import funds from an uncompatible wallet, the first recommendation is to just send the funds over. If that is not an option because the wallet is not functional anymore and all you have is your xpriv, then please use a compatible wallet or our [Masterscan](https://mycelium-com.github.io/masterscan/) tool.

If your intention is to use the same account as in your bitcoin core, then I'm sorry but Mycelium at this point only supports BIP44 and only supports one wallet plus any number of additional accounts.
