### ISSUE TITLE
Fee for Low-prio much higher than High-Prio for same transaction

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet#307]
![image](https://cloud.githubusercontent.com/assets/388716/19672147/1afb27da-9a42-11e6-9a85-66be80a591f0.png)

**Comment by Transisto** [comment]
It only happen between 0.097 and 0.10008

0.0001 = 0.10729, 0.13139, 0.1481, 0.3108 (priority)
0.001 = 0.10729, 0.13139, 0.1481, 0.3108 (priority)
0.01 = 0.18227, 0.223, 0.251, 0.528 (priority)
0.02 = 0.10729
0.03 = 0.25724
0.04 = 0.4072
0.05 = 0.55716
0.06 = 0.70712
0.07 = 0.85708
0.08 = 1.00704
0.09 = 1.157
0.097 = 1.23197, 1.508, 1.69735, **3.5688** (priority)
0.098= 1.23197, 1.508, 1.69735, **0.3108** (priority)
0.099= 1.23197, 1.508, 1.69735, 0.3108 (priority)
0.10008 = **1.23463**, 0.13139, 0.14781, 0.3108 (priority)
0.10009 = **0.10729**, 0.13139, 0.14781, 0.3108 (priority)
0.2 =*0.10729, 0.13139, 0.14781, 0.3108 (priority)

![image](https://cloud.githubusercontent.com/assets/388716/19672603/08dbd064-9a46-11e6-8b94-efbd2259bf96.png)

**Comment by DanielWeigl** [comment]
Hello - thank you for investigating it thoroughly and reporting it. 

Yes - you are completely correct, thats due to the coinselection algorithm, that tries to first spend confirmed outputs and if it does not have enough to cover the funds, it will also include unconfirmed ones.

We already imagined that might lead to strange corner cases, where the selection changes completely depending on the amount to spend, but so far never seen it "in the wild"

**Comment by Giszmo** [comment]
With #304 fixed, this issue would probably have been less confusing.
