### ISSUE TITLE
Low-prio fees too high

### ISSUE THREAD

**Issue by rebroad** [mycelium-com/wallet#316]
I sent a transaction 2 days ago and chose the lowest priority fee possible, which was still quite high IMHO. Anyway, was rather disappointed to see it get into a block within 40 minutes from broadcasting, which would suggest the fee was far higher than it needed to be? It was not an urgent transaction, and I would have been happy for it to have taken more than 24 hours to get into a block. Can there please be a way to allow me to reduce the fee even lower? Perhaps even specify the fee manually?

**Comment by DanielWeigl** [comment]
You are right, we are staying on the more higher side for the low fee. The reason is that most user dont really understand what a too low fee means and we have no option to support them if their transactions get locked up. 

Secondly, its very hard to determine what the correct fee for the next n block is. It is a very random process and it can even change quite quickly. So a transaction that has the right fee for the next 10 blocks, might have a way too low fee if after 1h the mempool load increases a lot. Therefor we try to err on the higher side, rather than the lower.

**Comment by Giszmo** [comment]
If we had a way of handling the support, a lower fee would be nice for donations and other non-urgent stuff but that's definitely a power user feature we can't throw at all our users. If anybody wants to implement some "tab 12 times on the lower left corner on that screen to activate super low fees", be my guest but else this is not a bug but a feature (to reduce confusion with our users).

**Comment by rebroad** [comment]
@DanielWeigl give users some credit please - as long as the message displayed is clear (e.g. this transaction may take up to 24 hours or longer to confirm) then we should certainly make low priority txs low priority - within 30 minutes confirmation is clearly not low priority and therefore is misleading and arguably fraudulent.
