### ISSUE TITLE
Fee is higher than the transaction itself 

### ISSUE THREAD

**Issue by jalte** [mycelium-com/wallet#338]
Hi there, 
I'm trying to send 10,000 satoshi to a friend. As part of bitcoin awareness demonstration program. 

However I noticed that the fee is higher than the transaction itself, around 15,000 satoshi for low-prio and up to 40,000 satoshi for priority fee. 

How can I manually set to a lower fee?

**Comment by Giszmo** [comment]
Hi @jalte 

your bitcoin awareness demonstration program is highly appreciated, at least by me personally :smile: 

Please read up a bit on how fees work though. Fees are not proportional to the value you are sending but to the size in bytes. A typical transaction is 300 to 1200 bytes in size, which already accounts for a range of x4 in transaction fees. People collecting really small outputs run into much higher fees when they try to send a resulting 15000 bytes transaction.

The mining fee is thus expressed as Satoshis per byte, or sat/B in short. Current network load ran the bidding up to 140sat/B as a very common price for a high priority transaction and 70sat/B for a 20 block target, which is our lowest priority. Going lower runs the risk of the transaction not confirming ever, which is why we are not inclined to facilitate lower fees.

P.S.: I removed your url-shortened links. Feel free to add them back in without url shortening. `[this](http://www.damnlongurlworthshorteni.ng)` for example looks like [this](http://www.damnlongurlworthshorteni.ng).
