### ISSUE TITLE
35 % fee on a 300 euro low-prio transaction?

### ISSUE THREAD

**Issue by gitottof** [mycelium-com/wallet#340]
attempted to send 300 euro worth of bitcoin to an exchange account and even the low-prio fee amounts to 50 euro? Normal charges 80 euro. Needless to say i did not go through with the transaction. I sincerely hope this is a bug that gets fixed soon. If not, it's daylight robbery.

**Comment by vnnkl** [comment]
How big are your inputs?

This problem is mostly encountered by users using either faucets or cloud mining.
You can let the wallet display all addresses which hold a balance for you, your wallets balance is the sum of all these outputs, please see the link below to our FAQ where we explain in more detail, how to show your unspent outputs.
http://support.mycelium.com/hc/en-us/articles/206335739

If you have the majority smaller than lets say 1 euro, then this is the reason. 
It is an issue you will encounter with other wallets as well, as you need to pay an fee proportional to your transactions size, otherwise your transaction is not of interest for miners and never gets confirmed.

If you use a service that generates those, set the minimum payout to a threshold that creates usable UTXOs.

You can message me at support@mycelium.com

Greetings

**Comment by Giszmo** [comment]
I labled this `question` until @gitottof replies with more details. 50€ fees is gigantic but if the transaction spends 150 UTXOs I wouldn't be too surprised neither.
