### ISSUE TITLE
Ad-free version

### ISSUE THREAD

**Issue by chill117** [mycelium-com/wallet#360]
Hello, Mycelium Team.

I have been using the Mycelium android mobile wallet for years. It has been my number one recommendation for wallet app for new users. Thank you for all the work you've done on this project.

With that said, I am a bit annoyed to discover this morning that there are now display advertisements on the main screen of the Mycelium wallet app. Can we discuss possible ways to remove these advertisements?

My recommendations (in order of preference):
* Remove the ads entirely
* Paid version which has display ads disabled

-----------

Additional questions that this brings to my mind:
* Who is receiving the revenue from these advertisements?
* What are the funds used for?
* Did the "crowd sale" not yield enough funds for the on-going development/maintenance of the wallet app?
* Is there a long-term vision/plan available regarding the Mycelium wallet app that is publicly accessible?
* Has this project / the Mycelium team been bought/sold recently?

Perhaps I am way off base on some of these questions, but I feel that answers to the above questions are important in determining if I will continue to use and trust this wallet application.

Thank you and regards,
chill

**Comment by Giszmo** [comment]
I would like to accept the feature request as I agree that the ads are very intrusive the way they are now. Mycelium did monetize on its users before. For example the links to buy a Trezor/Ledger/Keepkey were referral links but they were well hidden, so they didn't cause the allergic reaction that our new main-screen referral links cause, so I would like you to see this a bit in proportion. It's just a design choice.

To my knowledge did the upper management of Mycelium not change. I took over as lead Android dev from Daniel Weigl in February and thus had the questionable honor to release this latest version. I did my best to improve transparency, which is why you now see many more names and commits in the hope to provide a more attractive repository to contribute to.

As Mycelium has server, development and support expenses every month, we also need to earn money somehow and we try to do that without loosing our reputation as a feature-rich, high quality tool for bitcoiners.

While it is not my call, I would suggest some more options on how to make the app less annoying regarding ads:

* move the ads down a bit - it's not our intention to have users click them accidentally. We don't get paid for clicks
* make the ads less clunky - the buttons are really not nice
* add a [x] button to dismiss or collapse ads for a day or a month - collapse would probably be better as it would avoid the situation where a user clicks the ad away for a month and a minute later realizes that having a Trezor would actually make a lot of sense and goes to buy it without referral code
* show no ads for the first month or two - users struggle enough understanding bitcoin. Some waitress that just got her first bitcoin tip will not buy a Ledger right away

**Comment by chill117** [comment]
Hello and thank you for taking the time to respond to this request.

> For example the links to buy a Trezor/Ledger/Keepkey were referral links but they were well hidden, so they didn't cause the allergic reaction that our new main-screen referral links cause, so I would like you to see this a bit in proportion. It's just a design choice.

This makes sense. The main screen ad, as is, does consume entirely too much screen space (~15% of the vertical space). Perhaps this could be replaced with a simple (and small) text link that shows a separate full screen view with all the referral advertisements in one place? I think the link text could be something like this: "Looking for more ways to use bitcoin securely?"

> As Mycelium has server, development and support expenses every month, we also need to earn money somehow and we try to do that without loosing our reputation as a feature-rich, high quality tool for bitcoiners.

This is what I suspected, and I understand completely. Is there a publicly accessible financial report for the Mycelium project? This could help users understand the financial needs of the project, and might make them more willing to support it financially.

> I did my best to improve transparency, which is why you now see many more names and commits in the hope to provide a more attractive repository to contribute to.

Thank you for your efforts in this area. I think openness and transparency, in a project like this, are critical to maintaining trust.

> While it is not my call, I would suggest some more options on how to make the app less annoying regarding ads:

Who makes these decisions?

**Comment by Giszmo** [comment]
I guess secondary screen is not going to happen but the original screenshot for the merge request looked much nicer. I'm pretty sure we get this improved soon.

**Comment by chill117** [comment]
I am not sure if you did it intentionally, but you've ignored my question twice:
* Who makes decisions that affect the development of this wallet app?

This was a bad decision all around. There are a couple active reddit threads with outraged users, some of which make some solid points as to why this was a bad move:
* https://www.reddit.com/r/Bitcoin/comments/6fkcny/mycelium_just_been_updated_and_it_now_has_ads/
* https://www.reddit.com/r/Bitcoin/comments/6fhfrd/deleting_mycelium_because_of_ads_what_are/

**Comment by Mrpinkypants** [comment]
Absolutely terrible move. I'll be deleting this app if ads aren't removed.

At least give an option for a paid version if you want to monetize it!
I would pay a one off fee of $2 ... I am not going to use a wallet with ads period. 

No way I'm clicking on an add through a wallet on my phone... utterly ridiculous move. 

You'll be seeing your Play store rating tank unless you address this.

**Comment by Kixunil** [comment]
> As Mycelium has server,

I'd love to offload your server by redirecting to my own full node. It isn't possible, is it?

**Comment by drewdotpro** [comment]
If only there was some kind of internet currency people could use to pay a one off fee, eh?

Joking aside, these ads are a travesty. Please make them stop.

**Comment by samurai321** [comment]
why don't put the ads in their own tab, "sponsored content" , people are curious and will look anyway. 

also, why don't add modules with altcoins, and shapeshift integration, you could get some revenue from shapeshift referral fees.  

just don't clutter the app with ads because people have smartphones with small screens as backup.

**Comment by Giszmo** [comment]
I was asked by Alexander Kuzmin (to answer @chill117 that's the guy who decides stuff but lots of stuff is also decided by our product manager @jeromerousselot or just done by devs and released by currently me) to remove ads and what I heard, they will probably come back in a sponsored content tab as mentioned by @samurai321.

I will close this issue for now. Non-Ad-related stuff I will ignore for now. This is not how issue trackers work. Please contact us on social media, info@mycelium.com or open new issues.

version 2.8.11 was released to the playstore and has no ads on the main screen.

**Comment by chill117** [comment]
Thank you for the information and for the quick turn-around on this issue.

**Comment by Mrpinkypants** [comment]
Very welcome, thanks for listening to your users!

Best wallet available!


⁣Sent from BlueMail ​
