### ISSUE TITLE
New Bussinesses Tab has "Add Address"

### ISSUE THREAD

**Issue by buch8** [mycelium-com/wallet#370]
Addressbook lacks "Add Address"

I retranslated from the German version. So excuse me, if I didn't use the exact English terms.

**Comment by dscotese** [comment]
I just noticed this too.  I imagine that the indexing for which tab has which button was not updated properly when they added the businesses tab.

**Comment by Giszmo** [comment]
Hi. Thanks for reporting. Together with the "Can't create contacts on the Address book tab" this will be fixed in the next release.

**Comment by dscotese** [comment]
Thanks Giszmo.  I've been looking through the code to see if i could see where it went wrong but I only got as far as identifying "AddDialog" as a function that is called from code that no longer runs.  If you have interest, perhaps you could tell me what file specifies that an icon should be displayed above the contents of a given tab (for example, that the icon for adding an address book entry should be above the Address Book tab instead of the Business tab) and I could take a look.  No worries if you don't have time!

**Comment by Giszmo** [comment]
fixed
