### ISSUE TITLE
Is there anyway to recover a forgotten PIN # on my personal Android phone??

### ISSUE THREAD

**Issue by guitarfax** [mycelium-com/wallet#38]

**Comment by bitcoinme** [comment]
Thanks a lot guys!!!

Safed me 0.2 BTC!
I copied the file to external storage by using cp settings.xml /external_sd
From there I could open it with a file manager and view the file in the editor

**Comment by 2pac1** [comment]
What you could try is:

Get the second phone, same as this one to test it on first multiple times if needed.
Once you are confident with backup phone, then move to real device.

1. unlock the bootloader, being careful not to lose any data
2. install TWRP
3. boot into TWRP and then go to >> TERMINAL
4. Navigate to: /data/data/com.mycelium.wallet/shared_prefs/
(cd /data/data/com.mycelium.wallet/shared_prefs/)
5. Then do the: cat settings.xml
(that should list the contents of the file and you should find the PIN saved within the text as a clear text).

This has been tested and verified on:
Phone: Nexus 5 (not rooted)
Android OS: 6.0.1
Bootloader: unlocked (in order to install TWRP)
TWRP: installed, 3.3.1-0

**Comment by Zab0x** [comment]
> For future references, what one could try is:
> 
> Get the second phone, same as this one to test it on first multiple times if needed.
> Once you are confident with backup phone, then move to real device.
> 
> 1. unlock the bootloader, being careful not to lose any data
> 2. install TWRP
> 3. boot into TWRP and then go to >> TERMINAL
> 4. Navigate to: /data/data/com.mycelium.wallet/shared_prefs/
>    (cd /data/data/com.mycelium.wallet/shared_prefs/)
> 5. Then do the: cat settings.xml
>    (that should list the contents of the file and you should find the PIN saved within the text as a clear text).
> 
> This has been tested and verified on:
> Phone: Nexus 5 (not rooted)
> Android OS: 6.0.1
> Bootloader: unlocked (in order to install TWRP)
> TWRP: installed, 3.3.1-0

Hi 2pac1, i have forgotten my Pin and i'm not really tech savy so it would be very helpfull if you could help me.

I use a Samsung S10 Note 

Is it possible to extract it from there?

I'm very thankfull for any help cause i'm not able to do it myself 🙄🙏🏻

**Comment by Giszmo** [comment]
# WARNING!!!

The above methods are not recommended by Mycelium and we do not vet them in any way. You might lose your coins to a scammer. You might destroy your phone. Be careful!

The PIN protection is a feature and we do not endorse any way of circumvention but can't rule out that experts would be able to reset the PIN in any way.

**Comment by Zab0x** [comment]
Hi there,

thank you for your help and i will be careful 🙏🏻
As you mentioned in you reply " experts may be able to help "
Could you recommend me towards a expert who can help me?

I'm pretty lost arm, cause i can't remember my Pin 🙄.

Would be thankfull if me as not tech savy someone could help me.

All the best 🙏🏻

Leo Wandersleb <notifications@github.com> schrieb am Di., 9. März 2021,
02:25:

**Comment by 2pac1** [comment]
The above method only works if you could unlock the bootloader without
wiping the data. And if you could put custom recovery (twrp), also without
wiping.

If that doesn't work then it's down to:
1. Data extraction from the chip
2. Privilege escalation exploit
3. Having Mycelium give you debugable version of the app which you can run
as "run as" via console.

The above scenario happened to John Doe where somehow she/her now has a new
mycelium wallet on a new phone without writing down the seed or setting the
pin themselves.

Don't know if that is a bug that could happen.
Old phone has different wallet.

And sorry @zab0x I cannot help you.
I posted here just for anyone else who might run into this problem in the
future.

And for Mycelium team >>  there is a potential security improvement that
could be done.
If one deletes the data/data/com.mycelium.wallet/shared_prefs/settings.xml
the pin will be removed upon restarting the app. But when you want to set
pin again, it will not ask you to verify the seed, like it did ask the
first time when you have set the pin.
It should ask you to verify the seed each and every time if you are setting
a spending pin.
Because if not, you might end up in situation where you don't have seed and
cannot enter pin.

**Comment by code-vagabond** [comment]
I used a version of Mycelium a few years back which still allows for unlimited retries when inputting the PIN, yours might be as well.

I'm currently cracking my PIN by connecting my old phone to a computer, stream the screen and wrote some script to try out all 1000 000 possible combinations.

I might be able to help, just ping me a line on Twitter (https://twitter.com/codevagabond)

**Comment by Giszmo** [comment]
Android does not allow to down-grade the app to an older version. To install an old version, you either have to delete the app with its data or you need access that would allow to extract the key or delete the pin trivially anyway.

**Comment by code-vagabond** [comment]
> Android does not allow to down-grade the app to an older version. To install an old version, you either have to delete the app with its data or you need access that would allow to extract the key or delete the pin trivially anyway.

Yes I was referring to people who still have the older version on their phone. The brute-force worked for me!
